### ISSUE TITLE
Historic Event Data

### ISSUE THREAD

**Issue by sb185456** [seatgeek/api-support#127]
I am working on a sales forecasting application where we are attempting to see how local events impact sales at nearby restaurants.

This API is great for getting information on upcoming events, but is there any way to get information about events that have happened in the past?

For the development of the application, I have historic restaurant transactions for about a year between June 2021 and July 2022, so I was hoping to get event data for the same time period if possible.

Essentially, I'm wondering if it will ever be possible to provide "start_date" and "end_date" arguments to the `https://api.seatgeek.com/2/events` endpoint in addition to `lat`, `lon`, and `range` so that I can get historic events that occurred close to the restaurants that I have historic data for.

Thanks!

**Comment by sddamico** [comment]
Hey @sb185456, unfortunately today we do not offer a method for querying past events from our API and we do not have plans for adding that functionality.

**Comment by sb185456** [comment]
Hey thanks for the quick response @sddamico - would historical event data ever be available for a **paid** version of the API? Does SeatGeek hold on to historical event data or scrub when the event passes? 

Trying to understand if that data even exists, and if so, would a partnership open those doors. No worries if not, just trying to be thorough in my exploration.

**Comment by sddamico** [comment]
A little "how the sausage is made" to explain why we don't have a past events API:

Our "event catalog" APIs that allow for querying events/performers/venue are served through elasticsearch on the backend. We rebuild our elastic index each night and only populate it with upcoming events since that is generally what makes the most sense for our consumer product and it reduces our index size dramatically.

We retain past events in the DB that we populate the index from, but we don't have an API for querying those events from the DB today. In places where we need to reference those past events in our product, we query the DB directly since it's not a heavy load.

We have no plans to build an API to expose things directly from our DB today.

I've forwarded this thread internally to our head of external APIs and will give him an opportunity to follow up further.

**Comment by sb185456** [comment]
Thanks again for the quick response and the additional context! This all makes a lot of sense.
