### ISSUE TITLE
Question about image sizes

### ISSUE THREAD

**Issue by Bkind7** [seatgeek/api-support#27]
Got this question from a partner and don't have the best response. They want to pull smaller image sizes from the API than `huge`. I encouraged them to try other endpoints such as `small` and `medium`. Here's what they said:

>Yeah I did that, hit the performer endpoint like so: http://platform.seatgeek.com/#performers

>but unfortunately i didn't find too many results with more than one image in the response and they are usually in the 'huge' category. like so:

>{u'huge': u'https://chairnerd.global.ssl.fastly.net/images/performers-landscape/seu-jorge-d6f136/4794/huge.jpg'} 

>I'd like to pull data daily for my site and I don't want to abuse the system/API. Is there a way to maybe filter in the initial request and just receive results that have images included.

**Comment by josegonzalez** [comment]
We encourage people to cache our entire API daily - maybe twice daily in the case of sports schedule releases happening later in the day - for their own app performance reasons, which is well within our terms of use.

It's perfectly fine for the partner to do the above and filter on their end for performers that have images. At the moment, there isn't a way to filter by performers with images, and because of how we offer the data, we have no plans to implement such functionality.
