### ISSUE TITLE
Quick question on reschedules

### ISSUE THREAD

**Issue by micada** [seatgeek/api-support#42]
Hi there! So I am interested in accurate to the day information about that day's baseball games (and secondarily, events happening at baseball parks). While not common, there are the occasional cancels and then reschedules. How does the Seatgeek API handle the canceled event, the new event and how quickly/often is this information updated through the API. In another issue, you suggested ingesting the API once a day, whenabouts is the best time? And again, how quickly from when a game/event is canceled - let's say, due to inclement weather - is it reflected in the API?

Thanks!

**Comment by stephenyeargin** [comment]
My observation (read: I don't work for SeatGeek, but do use it) is that the rescheduled event can be:

- an update of the existing record (the start time changes to the new date, the event title includes a note)
- a new entry entirely (with the event title indicating which game it superseded)

I pull from the API at 4 a.m. and ignore/hide any event that is time TBA or date TBA. If an event that was previously scheduled for a future time now returns a 404, I presume it was canceled. This is particularly the case with playoff games after a team has been eliminated.

**Comment by josegonzalez** [comment]
Sorry for the late response but here is our official stance:

- We update data as often as is necessary. In some cases, we may need to mark an event as rescheduled, merged (because our data may occasionally have duplicates) or canceled. These happen periodically, and I cannot give you a given time when we would populate such info into our dataset. For instance, an artist may cancel a tour at 6pm, or a game may be canceled due to inclement weather an hour before the game. Once we know this is occurring, the changes are reflected in our API in near real-time.
- Generally speaking, I would say you are free to scrape our dataset a few times a day to keep it fresh. We do not currently have set rate limits, though I would handle api response codes as appropriate.

Hope that helps you (and others).
