### ISSUE TITLE
Filter events modified or added since a certain time?

### ISSUE THREAD

**Issue by pdxrlk** [seatgeek/api-support#53]
What is the recommended way to query for events which have been added or modified since the last time I checked? I don't see any arguments which would help. Thanks.

**Comment by josegonzalez** [comment]
I believe you can query for `created_at`, but we don't have any method of searching `updated_at`. This is because pricing data changes pretty frequently, meaning that the `updated_at` field would change pretty often.

As an alternative, I suggest you download our entire index a few times a day and compare the dataset to wherever you are storing the records.

**Comment by josegonzalez** [comment]
Closing as I believe this was adequately answered.
