### ISSUE TITLE
Affiliate Link Failure

### ISSUE THREAD

**Issue by adhadley** [seatgeek/api-support#57]
I just tried out using a tracking URL with my unique aid number but it didnt work.
I bought the ticket after clicking on this link and it has not register an an affiliate ticket sale.

Am I doing something wrong?
my aid ID number is: 13055 
 
This is the URL i used : https://seatgeek.com/heat-at-hornets-tickets/1-20-2018-charlotte-north-carolina-spectrum-center/nba/3995085?oq=heat+at+hornets+tickets+1+20+2018+charlotte+north+carolina+spectrum+center+nba+3995085aid+13055

**Comment by josegonzalez** [comment]
I believe you need to set the AID like so:

```
 https://seatgeek.com/heat-at-hornets-tickets/1-20-2018-charlotte-north-carolina-spectrum-center/nba/3995085?oq=heat+at+hornets+tickets+1+20+2018+charlotte+north+carolina+spectrum+center+nba+3995085&aid=13055
```

You'll notice I separated it via ampersand (`&`) and also made it a key/value in the querystring.

Let me know if that helps.

**Comment by adhadley** [comment]
What do you mean by made it a key/value in the querystring? sorry not familiar with that

**Comment by adhadley** [comment]
Also When I send myself a text message with that URL it doesnt keep the &aid=13055 
is this supposed to happen?

**Comment by josegonzalez** [comment]
Shorter example:

```
# *just* your aid is in the query string, which is delimited from the rest of the url with `?`
https://seatgeek.com/?aid=13055

# with another key/value pair in the querystring, as you had in your example
https://seatgeek.com/?oq=some-other-thing&aid=13055
```

The cruq of the issue is that your link had a separate key/value pair in the existing querystring, so you needed to separate yours with `&` from the existing ones. [Here](https://stackoverflow.com/questions/39266970/what-is-the-difference-between-url-parameters-and-query-strings) is a stack overflow link that has a reasonable (to me at least) description of the parts of a url and how to manipulate them.

As far as sending yourself a text message, I don't know what the issue there might be. I would check on whatever script you are using to send urls to ensure that querystring parameters are properly persisted. You might be coming up against the SMS character limit for your specific provider.

**Comment by zackkitzmiller** [comment]
> Also When I send myself a text message with that URL it doesnt keep the &aid=13055
is this supposed to happen?

Yes. When you hit the SeatGeek web application we store the aid in a cookie and strip it from the URL.

**Comment by adhadley** [comment]
When I put &aid=13055 at the end of this link: 

https://seatgeek.com/magic-at-celtics-tickets/1-21-2018-boston-massachusetts-td-garden/nba/3993300?oq=magic+at+celtics+tickets+1+21+2018+boston+massachusetts+td+garden+nba+3993300

and then i click on it, it does not work --> the &aid=13055 does not stick to the end of the link when i clink on that link. The Same thing happens with i do ?aid=13055 at the end.

Is there a different form I should be using?

**Comment by zackkitzmiller** [comment]
That is intentional. We store the aid on the users browser. It will be removed from the URL at that time.

**Comment by josegonzalez** [comment]
Closing as I think this was resolved.
